### ISSUE TITLE
Thing `<<` is not defined

### ISSUE THREAD

**Issue by lhutzelmann** [KarolS/millfork#109]
Hi,
I just started to use millfork, so I wanted to compile the fire.mfk example for C64. The following error occurred when compiling with "C:\dev\c64\millfork\millfork-0.3.26\millfork.exe" "c:\Users\lars_\Documents\C64\VSC_workspaces\test\fire.mfk" -o "c:\Users\lars_\Documents\C64\VSC_workspaces\test\fire.prg" -t c64
for release 0.3.26 (same for last few releases).
`
Exception in thread "main" millfork.env.UndefinedIdentifierException: Thing `<<` is not defined
        at millfork.env.Environment.$anonfun$get$1(Environment.scala:345)
        at scala.Option.fold(Option.scala:251)
        at millfork.env.Environment.get(Environment.scala:347)
        at millfork.env.Environment.$anonfun$get$2(Environment.scala:347)
        at scala.Option.fold(Option.scala:251)
        at millfork.env.Environment.get(Environment.scala:347)
        at millfork.env.Environment.overlapsVariable(Environment.scala:2787)
        at millfork.compiler.AbstractStatementPreprocessor.$anonfun$optimizeStmt$12(AbstractStatementPreprocessor.scala:241)
        at millfork.compiler.AbstractStatementPreprocessor.$anonfun$optimizeStmt$12$adapted(AbstractStatementPreprocessor.scala:241)
        at scala.collection.Iterator.forall(Iterator.scala:955)
        at scala.collection.Iterator.forall$(Iterator.scala:953)
        at scala.collection.AbstractIterator.forall(Iterator.scala:1431)
        at scala.collection.IterableLike.forall(IterableLike.scala:77)
        at scala.collection.IterableLike.forall$(IterableLike.scala:76)
        at scala.collection.AbstractIterable.forall(Iterable.scala:56)
        at millfork.compiler.AbstractStatementPreprocessor.optimizeStmt(AbstractStatementPreprocessor.scala:241)
        at millfork.compiler.AbstractStatementPreprocessor.$anonfun$optimizeStmts$1(AbstractStatementPreprocessor.scala:55)
        at millfork.compiler.AbstractStatementPreprocessor.$anonfun$optimizeStmts$1$adapted(AbstractStatementPreprocessor.scala:54)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at millfork.compiler.AbstractStatementPreprocessor.optimizeStmts(AbstractStatementPreprocessor.scala:54)
        at millfork.compiler.AbstractStatementPreprocessor.optimizeStmt(AbstractStatementPreprocessor.scala:291)
        at millfork.compiler.AbstractStatementPreprocessor.$anonfun$optimizeStmts$1(AbstractStatementPreprocessor.scala:55)
        at millfork.compiler.AbstractStatementPreprocessor.$anonfun$optimizeStmts$1$adapted(AbstractStatementPreprocessor.scala:54)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at millfork.compiler.AbstractStatementPreprocessor.optimizeStmts(AbstractStatementPreprocessor.scala:54)
        at millfork.compiler.AbstractStatementPreprocessor.apply(AbstractStatementPreprocessor.scala:48)
        at millfork.compiler.mos.MosCompiler$.compile(MosCompiler.scala:19)
        at millfork.output.AbstractAssembler.compileFunction(AbstractAssembler.scala:776)
        at millfork.output.AbstractAssembler.$anonfun$assemble$14(AbstractAssembler.scala:286)
        at millfork.output.AbstractAssembler.$anonfun$assemble$14$adapted(AbstractAssembler.scala:285)
        at scala.Option.foreach(Option.scala:407)
        at millfork.output.AbstractAssembler.$anonfun$assemble$13(AbstractAssembler.scala:285)
        at millfork.output.AbstractAssembler.$anonfun$assemble$13$adapted(AbstractAssembler.scala:284)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at millfork.output.AbstractAssembler.assemble(AbstractAssembler.scala:284)
        at millfork.Main$.assembleForMos(Main.scala:295)
        at millfork.Main$.main(Main.scala:105)
        at millfork.Main.main(Main.scala)
`
Any ideas what went wrong?

**Comment by KarolS** [comment]
This has already been fixed together with #107.

I think I should make a new release as soon as possible. Thanks for the report.

**Comment by KarolS** [comment]
The fix has been officially released in 0.3.28
