### ISSUE TITLE
65CE02 JSR incorrect Assmbly 

### ISSUE THREAD

**Issue by oziphantom** [KarolS/millfork#116]
On a Mega65, so 65CE02 target, Given 
```
void EnterMonitor() {
	asm {
		pha
		lda #$f8 
		tsb $d030  //enable ROM
		pla
		jsr (BRKHandlerSave)
		lda #$f8 
		trb $d030 //disable ROM
	}
}
```
one gets
```
FATAL: Cannot assemble an unknown opcode (JSR,IndexedZ)
Exception in thread "main" java.lang.AssertionError: Cannot assemble an unknown opcode (JSR,IndexedZ)
        at millfork.error.ConsoleLogger.fatal(ConsoleLogger.scala:94)
        at millfork.output.MosAssembler$.opcodeFor(MosAssembler.scala:307)
        at millfork.output.MosAssembler.emitInstruction(MosAssembler.scala:60)
        at millfork.output.MosAssembler.emitInstruction(MosAssembler.scala:19)
        at millfork.output.AbstractAssembler.$anonfun$outputFunction$1(AbstractAssembler.scala:850)
        at millfork.output.AbstractAssembler.$anonfun$outputFunction$1$adapted(AbstractAssembler.scala:805)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at millfork.output.AbstractAssembler.outputFunction(AbstractAssembler.scala:805)
        at millfork.output.AbstractAssembler.$anonfun$assemble$51(AbstractAssembler.scala:447)
        at millfork.output.AbstractAssembler.$anonfun$assemble$51$adapted(AbstractAssembler.scala:439)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at millfork.output.AbstractAssembler.$anonfun$assemble$49(AbstractAssembler.scala:439)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
        at millfork.output.AbstractAssembler.assemble(AbstractAssembler.scala:438)
        at millfork.Main$.assembleForMos(Main.scala:295)
        at millfork.Main$.main(Main.scala:105)
        at millfork.Main.main(Main.scala)
```
which is right, there is no JSR,z but I'm also not using (JSR,z) just (JSR)

**Comment by KarolS** [comment]
Yeah, 65CE02 support is not complete. I fixed the basic 65CE02 instruction set, but the Mega65 extensions are still a future endeavour.
