### ISSUE TITLE
Problem compiling simple Hello world with milfork for X16 target on windows 10

### ISSUE THREAD

**Issue by ZerohPage** [KarolS/millfork#20]
I'm trying to compile a simple milfork hello world using the visual studio code plugin but getting :

ARGS: "D:\Dev\millfork-0.3.12\millfork.exe" "d:\Dev\millfork-0.3.12\hello.mfk" -o "d:\Dev\millfork-0.3.12\hello.prg" -fno-cmos-ops  -t x16_experimental
WARN:  JMP bug prevention should be enabled for non-CMOS architecture
ERROR: CMOS opcodes enabled for non-CMOS architecture
ERROR: Parse failed
FATAL: Build halted due to previous errors
Compile Error
Exception in thread "System-2" java.lang.AssertionError: Build halted due to previous errors
    at millfork.error.ConsoleLogger.fatal(ConsoleLogger.scala:93)
    at millfork.error.ConsoleLogger.assertNoErrors(ConsoleLogger.scala:108)
    at millfork.parser.AbstractSourceLoadingQueue.run(AbstractSourceLoadingQueue.scala:72)
    at millfork.Main$.assembleForMos(Main.scala:222)
    at millfork.Main$.main(Main.scala:90)
    at millfork.Main.main(Main.scala)

as you can see I added in -fno-cmos-ops as that is the only thing I could find that relates to the error message but it doesn't seem to make much difference.

Also tried for command line.

**Comment by KarolS** [comment]
Thanks for the report. It looks like I haven't tested my recent 65C02-related changes well enough.
For a quick workaround, open the `x16_experimental.ini` file and change:

    cpu=w65c02

to

    cpu=cmos

A proper fix is coming.
