### ISSUE TITLE
Output directory should be created if necessary

### ISSUE THREAD

**Issue by agg23** [KarolS/millfork#21]
Attempt to build without previously creating the `build` directory:

```
java -jar millfork.jar main.mfk -o build/rom.nes -t nes_small
```

```
Exception in thread "main" java.nio.file.NoSuchFileException: build/rom.nes
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:223)
        at java.base/java.nio.file.Files.write(Files.java:3488)
        at millfork.Main$.$anonfun$main$13(Main.scala:141)
        at scala.collection.immutable.Map$Map1.foreach(Map.scala:128)
        at millfork.Main$.main(Main.scala:125)
        at millfork.Main.main(Main.scala)
```

Instead, `build/` should be created.

**Comment by KarolS** [comment]
Thanks for the idea. It will be a part of the next release.
