### ISSUE TITLE
Assignment from dereferenced pointers can fail within loops on 6502

### ISSUE THREAD

**Issue by agg23** [KarolS/millfork#25]
Full repro, designed for NES (`-t nes_simple`), but similarly fails on `-t c64`:

```
struct Sprite {
    byte y
}

array(Sprite) sprites [20]
Sprite test

void main() {
    byte i
    test = Sprite(1)
    pointer.Sprite test_pointer
    test_pointer = test.pointer

    sprites[0] = Sprite(5)
    pointer.Sprite current_sprite
    current_sprite = pointer.Sprite(sprites.pointer)
    for i,0,until,20 {
        current_sprite->y = test_pointer->y
    }
}

void irq() {

}

void nmi() {

}
```

Throws the error:

```
Exception in thread "main" scala.NotImplementedError: an implementation is missing
        at scala.Predef$.$qmark$qmark$qmark(Predef.scala:288)
        at millfork.compiler.mos.MosExpressionCompiler$.compileAssignment(MosExpressionCompiler.scala:2241)
        at millfork.compiler.mos.MosStatementCompiler$.compile(MosStatementCompiler.scala:186)
        at millfork.compiler.AbstractStatementCompiler.$anonfun$compile$1(AbstractStatementCompiler.scala:14)
        at scala.collection.immutable.List.map(List.scala:290)
        at millfork.compiler.AbstractStatementCompiler.compile(AbstractStatementCompiler.scala:14)
        at millfork.compiler.AbstractStatementCompiler.compileWhileStatement(AbstractStatementCompiler.scala:44)
        at millfork.compiler.mos.MosStatementCompiler$.compile(MosStatementCompiler.scala:298)
        at millfork.compiler.AbstractStatementCompiler.$anonfun$compile$1(AbstractStatementCompiler.scala:14)
        at scala.collection.immutable.List.map(List.scala:286)
        at millfork.compiler.AbstractStatementCompiler.compile(AbstractStatementCompiler.scala:14)
        at millfork.compiler.mos.MosCompiler$.compile(MosCompiler.scala:19)
        at millfork.output.AbstractAssembler.compileFunction(AbstractAssembler.scala:670)
        at millfork.output.AbstractAssembler.$anonfun$assemble$10(AbstractAssembler.scala:237)
        at millfork.output.AbstractAssembler.$anonfun$assemble$10$adapted(AbstractAssembler.scala:236)
        at scala.Option.foreach(Option.scala:407)
        at millfork.output.AbstractAssembler.$anonfun$assemble$9(AbstractAssembler.scala:236)
        at millfork.output.AbstractAssembler.$anonfun$assemble$9$adapted(AbstractAssembler.scala:235)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at millfork.output.AbstractAssembler.assemble(AbstractAssembler.scala:235)
        at millfork.Main$.assembleForMos(Main.scala:262)
        at millfork.Main$.main(Main.scala:90)
        at millfork.Main.main(Main.scala)
```

This does successfully compile against Z80 targets.

**Comment by KarolS** [comment]
Thanks for your report.

This will be fixed in the next release.
