### ISSUE TITLE
FATAL: Value at index 0 is a Integer, not a Constant

### ISSUE THREAD

**Issue by agg23** [KarolS/millfork#38]
Combining `O3` or greater with `-fillegals`, along with some loop expression (perhaps `continue`), results in the following error:

```
FATAL: Value at index 0 is a Integer, not a Constant
Exception in thread "main" java.lang.AssertionError: Value at index 0 is a Integer, not a Constant
	at millfork.error.ConsoleLogger.fatal(ConsoleLogger.scala:93)
	at millfork.assembly.mos.opt.AssemblyMatchingContext.getImpl(RuleBasedAssemblyOptimization.scala:180)
	at millfork.assembly.mos.opt.AssemblyMatchingContext.get(RuleBasedAssemblyOptimization.scala:186)
	at millfork.assembly.mos.opt.UndocumentedOptimizations$.$anonfun$UseSbx$4(UndocumentedOptimizations.scala:137)
	at millfork.assembly.mos.opt.RuleBasedAssemblyOptimization.$anonfun$optimizeImpl$2(RuleBasedAssemblyOptimization.scala:70)
	at millfork.assembly.mos.opt.RuleBasedAssemblyOptimization.$anonfun$optimizeImpl$2$adapted(RuleBasedAssemblyOptimization.scala:59)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:877)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:876)
	at millfork.assembly.mos.opt.RuleBasedAssemblyOptimization.optimizeImpl(RuleBasedAssemblyOptimization.scala:59)
	at millfork.assembly.mos.opt.RuleBasedAssemblyOptimization.optimizeImpl(RuleBasedAssemblyOptimization.scala:98)
	at millfork.assembly.mos.opt.RuleBasedAssemblyOptimization.optimizeImpl(RuleBasedAssemblyOptimization.scala:98)
	at millfork.assembly.mos.opt.RuleBasedAssemblyOptimization.optimize(RuleBasedAssemblyOptimization.scala:50)
	at millfork.output.AbstractAssembler.$anonfun$compileFunction$2(AbstractAssembler.scala:699)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:89)
	at millfork.output.AbstractAssembler.compileFunction(AbstractAssembler.scala:698)
	at millfork.output.AbstractAssembler.$anonfun$assemble$13(AbstractAssembler.scala:261)
	at millfork.output.AbstractAssembler.$anonfun$assemble$13$adapted(AbstractAssembler.scala:260)
	at scala.Option.foreach(Option.scala:407)
	at millfork.output.AbstractAssembler.$anonfun$assemble$12(AbstractAssembler.scala:260)
	at millfork.output.AbstractAssembler.$anonfun$assemble$12$adapted(AbstractAssembler.scala:259)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at millfork.output.AbstractAssembler.assemble(AbstractAssembler.scala:259)
	at millfork.Main$.assembleForMos(Main.scala:276)
	at millfork.Main$.main(Main.scala:104)
	at millfork.Main.main(Main.scala)
```

Minimal repro:

```
array(byte) input [16] @ $300
const byte COUNT = 16

void main() {
    inner()
}

void inner() {
    byte j
    for j,0,until,COUNT {
        if input[j] == 0 {
            continue
        }
    }
}

void irq() {

}

void nmi() {

}
```

Built with `java -jar millfork.jar repro-optimize.mfk -o build/rom.nes -fillegals -t nes_small -O3`

**Comment by KarolS** [comment]
Thanks for the report, fixed!
