### ISSUE TITLE
problem with -t a8

### ISSUE THREAD

**Issue by zbyti** [KarolS/millfork#58]
```
java -jar millfork.jar --version
millfork version 0.3.18

java -jar millfork.jar -Xr -t a8 rainbow.mfk 

ERROR: (a8_os.mfk:23:12) `os_SEIOCB` has a non-constant value
       const byte os_SEIOCB  = 0*IOCBSZ      // ##rev2## screen editor IOCB index
                  ^
INFO:  Did you forget to import an appropriate module?
ERROR: (a8_os.mfk:23:27) The constant IOCBSZ is undefined
       const byte os_SEIOCB  = 0*IOCBSZ      // ##rev2## screen editor IOCB index
                                 ^
INFO:  Did you forget to import an appropriate module?
ERROR: (a8_os.mfk:24:12) `os_MAXIOC` has a non-constant value
       const byte os_MAXIOC  = 8*IOCBSZ      // first invalid IOCB index
                  ^
INFO:  Did you forget to import an appropriate module?
ERROR: (a8_os.mfk:24:27) The constant IOCBSZ is undefined
       const byte os_MAXIOC  = 8*IOCBSZ      // first invalid IOCB index
                                 ^
INFO:  Did you forget to import an appropriate module?
ERROR: (a8_os.mfk:681:12) Constant value 52224 too big for type byte
       const byte os_ICSORG = $CC00             // ##rev2## international character set origin
                  ^
ERROR: (a8_os.mfk:682:12) Constant value 57344 too big for type byte
       const byte os_DCSORG = $E000             // ##rev2## domestic character set origin
                  ^
ERROR: (a8_os.mfk:686:12) Constant value 58368 too big for type byte
       const byte os_EDITRV = $E400         // editor handler vector table
                  ^
ERROR: (a8_os.mfk:687:12) Constant value 58384 too big for type byte
       const byte os_SCRENV = $E410         // screen handler vector table
                  ^
ERROR: (a8_os.mfk:688:12) Constant value 58400 too big for type byte
       const byte os_KEYBDV = $E420         // keyboard handler vector table
                  ^
ERROR: (a8_os.mfk:689:12) Constant value 58416 too big for type byte
       const byte os_PRINTV = $E430         // printer handler vector table
                  ^
ERROR: (a8_os.mfk:690:12) Constant value 58432 too big for type byte
       const byte os_CASETV = $E440         // cassette handler vector table
                  ^
ERROR: (a8_os.mfk:694:12) Constant value 58448 too big for type byte
       const byte os_DISKIV = $E450         // vector to initialize DIO
                  ^
ERROR: (a8_os.mfk:695:12) Constant value 58451 too big for type byte
       const byte os_DSKINV = $E453         // vector to DIO
                  ^
ERROR: (a8_os.mfk:696:12) Constant value 58454 too big for type byte
       const byte os_CIOV   = $E456         // vector to CIO
                  ^
ERROR: (a8_os.mfk:697:12) Constant value 58457 too big for type byte
       const byte os_SIOV   = $E459         // vector to SIO
                  ^
ERROR: (a8_os.mfk:699:12) Constant value 58460 too big for type byte
       const byte os_SETVBV = $E45C         // vector to set VBLANK parameters
                  ^
ERROR: (a8_os.mfk:700:12) Constant value 58463 too big for type byte
       const byte os_SYSVBV = $E45F         // vector to process immediate VBLANK
                  ^
ERROR: (a8_os.mfk:701:12) Constant value 58466 too big for type byte
       const byte os_XITVBV = $E462         // vector to process deferred VBLANK
                  ^
ERROR: (a8_os.mfk:703:12) Constant value 58469 too big for type byte
       const byte os_SIOINV = $E465         // vector to initialize SIO
                  ^
ERROR: (a8_os.mfk:704:12) Constant value 58472 too big for type byte
       const byte os_SENDEV = $E468         // vector to enable SEND
                  ^
ERROR: (a8_os.mfk:705:12) Constant value 58475 too big for type byte
       const byte os_INTINV = $E46B         // vector to initialize interrupt handler
                  ^
ERROR: (a8_os.mfk:706:12) Constant value 58478 too big for type byte
       const byte os_CIOINV = $E46E         // vector to initialize CIO
                  ^
ERROR: (a8_os.mfk:708:12) Constant value 58481 too big for type byte
       const byte os_BLKBDV = $E471         // vector to power-up display
                  ^
ERROR: (a8_os.mfk:709:12) Constant value 58484 too big for type byte
       const byte os_WARMSV = $E474         // vector to warmstart
                  ^
ERROR: (a8_os.mfk:710:12) Constant value 58487 too big for type byte
       const byte os_COLDSV = $E477         // vector to coldstart
                  ^
ERROR: (a8_os.mfk:712:12) Constant value 58490 too big for type byte
       const byte os_RBLOKV = $E47A         // vector to read cassette block
                  ^
ERROR: (a8_os.mfk:713:12) Constant value 58493 too big for type byte
       const byte os_CSOPIV = $E47D         // vector to open cassette for input
                  ^
ERROR: (a8_os.mfk:715:12) Constant value 58496 too big for type byte
       const byte os_VCTABL = $E480         // RAM vector initial value table
                  ^
ERROR: (a8_os.mfk:716:12) Constant value 58496 too big for type byte
       const byte os_PUPDIV = $E480         // ##rev2## vector to power-up display
                  ^
ERROR: (a8_os.mfk:717:12) Constant value 58499 too big for type byte
       const byte os_SLFTSV = $E483         // ##rev2## vector to self-test
                  ^
ERROR: (a8_os.mfk:718:12) Constant value 58502 too big for type byte
       const byte os_PHENTV = $E486         // ##rev2## vector to enter peripheral handler
                  ^
ERROR: (a8_os.mfk:719:12) Constant value 58505 too big for type byte
       const byte os_PHUNLV = $E489         // ##rev2## vector to unlink peripheral handler
                  ^
ERROR: (a8_os.mfk:720:12) Constant value 58508 too big for type byte
       const byte os_PHINIV = $E48C         // ##rev2## vector to initialize peripheral handler
                  ^
ERROR: (a8_os.mfk:721:12) Constant value 58511 too big for type byte
       const byte os_GPDVV  = $E48F         // ##rev2## generic parallel device handler vector
                  ^
ERROR: (a8_os.mfk:725:12) Constant value 65530 too big for type byte
       const byte os_NMIVEC = $FFFA
                  ^
ERROR: (a8_os.mfk:726:12) Constant value 65532 too big for type byte
       const byte os_RESVEC = $FFFC
                  ^
ERROR: (a8_os.mfk:727:12) Constant value 65534 too big for type byte
       const byte os_IRQVEC = $FFFE
                  ^
ERROR: Codegen failed
FATAL: Build halted due to previous errors
Exception in thread "main" java.lang.AssertionError: Build halted due to previous errors
	at millfork.error.ConsoleLogger.fatal(ConsoleLogger.scala:94)
	at millfork.error.ConsoleLogger.assertNoErrors(ConsoleLogger.scala:109)
	at millfork.Main$.assembleForMos(Main.scala:296)
	at millfork.Main$.main(Main.scala:105)
	at millfork.Main.main(Main.scala)

```

**Comment by zbyti** [comment]
It's not a problem for me (I prepared my own a8.ini) because i don't use these modules anyway.

**Comment by KarolS** [comment]
Thanks for noticing! I haven't done much work for Atari, so I have missed it. Fixed.
