### ISSUE TITLE
Array `flags` has non-constant length

### ISSUE THREAD

**Issue by zbyti** [KarolS/millfork#83]
```
java -jar millfork.jar -O0 -t a8 montecarlo_pi_benchmark.mfk 
ERROR: (montecarlo_pi_benchmark.mfk:34:3) Array `flags` has non-constant length
         array(bool) flags[size] align(1024)
         ^
INFO:  Did you forget to import an appropriate module?
ERROR: (montecarlo_pi_benchmark.mfk:34:21) The constant size is undefined
         array(bool) flags[size] align(1024)
                           ^
INFO:  Did you forget to import an appropriate module?
ERROR: Codegen failed
FATAL: Build halted due to previous errors
Exception in thread "main" java.lang.AssertionError: Build halted due to previous errors
	at millfork.error.ConsoleLogger.fatal(ConsoleLogger.scala:94)
	at millfork.error.ConsoleLogger.assertNoErrors(ConsoleLogger.scala:109)
	at millfork.Main$.assembleForMos(Main.scala:296)
	at millfork.Main$.main(Main.scala:105)
	at millfork.Main.main(Main.scala)
```
but
```
java -jar millfork.jar -O4 -t a8 montecarlo_pi_benchmark.mfk 
```
works

**Comment by agg23** [comment]
How is `size` declared?

**Comment by zbyti** [comment]
Intersesting... It's some chunk code from other test I made. Shame on me :]

https://github.com/KarolS/millfork/blob/master/examples/a8/montecarlo_pi_benchmark.mfk

**Comment by agg23** [comment]
Sounds like you need the language server to help tell you that :P

**Comment by zbyti** [comment]
I'm was sure that code is valid. I have a proper XEX with -Xr
