### ISSUE TITLE
Imports are deduped via name, not via path

### ISSUE THREAD

**Issue by agg23** [KarolS/millfork#89]
It seems that imports take into consideration the entire `import ${value}` string, rather than the resolved path of that import, for determining whether or not a module needs to be parsed. This results in issues if you use relative/local imports in a subdirectory (e.g. `import foo`), and path imports from outside that subdirectory (`import bar/foo`).

Repro:
```
// main.mfk

import sub/import1
import sub/import2

void main() {
  output1 = 1

  add_output(5)

  output1 = output2

  while(true) {}
}

void nmi() {

}

void irq() {

}
```

```
// sub/import1.mfk

import import2

byte output1

void add_output(byte addition) {
  output2 = output1 + addition
}
```

```
// sub/import2.mfk

byte output2
```

Compiled with `java -jar millfork.jar main.mfk -o build/rom.nes -t nes_small`

```
ERROR: (import2.mfk:1:7) `output2` is already defined
       byte output2
             ^
...
ERROR: Codegen failed
FATAL: Build halted due to previous errors
Exception in thread "main" java.lang.AssertionError: Build halted due to previous errors
	at millfork.error.ConsoleLogger.fatal(ConsoleLogger.scala:100)
	at millfork.error.ConsoleLogger.assertNoErrors(ConsoleLogger.scala:115)
	at millfork.Main$.assembleForMos(Main.scala:320)
	at millfork.Main$.main(Main.scala:129)
	at millfork.Main.main(Main.scala)
```

**Comment by KarolS** [comment]
Fixed in 0.3.26
